#sisi_web_front_office_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: SfWebAppFrontOfficeBundle:Default:index }


sisi_web_front_office_homepage:
    path:     /
    defaults: { _controller: SfWebAppFrontOfficeBundle:Default:index }

# SECURITY
sisi_web_front_office_security:
    resource: "@SfWebAppFrontOfficeBundle/Resources/config/routing/security.yml"





