#sisi_web_back_office_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: SfWebAppBackOfficeBundle:Default:index }


# SECURITY
sisi_web_back_office_security:
    resource: "@SfWebAppBackOfficeBundle/Resources/config/routing/security.yml"

# BACKOFFICE
sisi_web_back_office_bo:
    resource: "@SfWebAppBackOfficeBundle/Resources/config/routing/backoffice.yml"

